echo ""
echo "🎉================================🎉"
echo "   Installation completed successfully!"
echo "🎉================================🎉"
echo ""
echo "📊 System Information:"
echo "   PHP Version: $(php --version | head -n 1)"
echo "   Nginx Status: $(systemctl is-active nginx)"
# shellcheck disable=SC2046
PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
echo "   PHP-FPM Status: $(systemctl is-active php"${PHP_VERSION}"-fpm)"
echo ""
echo "🌐 Access URLs:"
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "   Panel URL: http://${SERVER_IP}/"
echo "   Local URL: http://localhost/"
echo ""
echo "📝 Next steps:"
echo "   1. Configure your .env file if needed"
echo "   2. Set up SSL certificate (recommended)"
echo "   3. Configure firewall rules"
echo "   4. Test the panel by accessing the URL above"
echo ""
echo ""
echo "✅ Installation process completed!"
echo "🔍 Check the panel at: http://${SERVER_IP}/"
